spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.cgqsduwzty6j.us-east-2.rds.amazonaws.com:5432/demo01
    username: huanfu
    password: 62851030
    pool-size: 30